server:
  port: 8081
spring:
  application:
    name: tuling-admin
  datasource:
    druid:
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      validation-query: SELECT 1
    dynamic:
      primary: user
        # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        user:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_user?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        goods:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_goods?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        promotion:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_promotion?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        normal:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_normal?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        order:
          url: jdbc:mysql://192.168.65.223:3306/tl_mall_order?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
#    url: jdbc:mysql://192.168.65.71:3306/tl_mall_user?characterEncoding=utf-8&useSSL=false
#    username: tlmall
#    password: tlmall123
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.65.206:8848,192.168.65.209:8848,192.168.65.210:8848 #配置中心的地址
        file-extension: yml #配置文件结尾的配置

mybatis-plus:
  mapper-locations:
    - classpath:dao/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /upload/product/**
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FpbYgfc4aFuYb6Hmsmx # 访问身份验证中用到用户标识
    accessKeySecret: LxBceRPR9pd7S6R46dd6ce2avxfVjZ # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: tuling-mall # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://yangguo.natapp1.cc/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: tulingmall/images/ # 上传文件夹路径前缀

upload:
  product:
    images: D:/temp/product/images
